This notebook uses the processed dataset obtained during the preprocessing stage. The goal of this stage is to prepare a numerical representation of hotels and calculate their similarities. The first step uses a feature-based approach: hotels are compared using purified categorical features, numerical features, and service lists.

In [6]:
!pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence_transformers)
  Downloading transformers-5.12.1-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (1.14.0)
Requirement already satisfied: torch>=1.11.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (2.12.0)
Requirement already satisfied: numpy>=1.20.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (1.11.4)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\anaconda\lib\site-packages (from sentence_transformers) (4.65.0)
Requirement already satisfied: filelock>=3.10.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (6.0.1)
Requirement already satisfied: typer>=0.20.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.25.1)
Requirement already satisfied: joblib>=1.1.1 in c:\anaconda\lib\site-packages (from scikit-learn>=0.22.0->sentence_transformers) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda\lib\site-packages (from scikit-learn>=0.22.0->sentence_transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence_transformers) (68.2.2)
Requirement already satisfied: sympy>=1.13.3 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1)
Requirement already satisfied: jinja2 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1.3)
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from tqdm>=4.0.0->sentence_transformers) (0.4.6)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=4.41.0->sentence_transformers)
  Downloading regex-2026.5.9-cp311-cp311-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     ---------------------------------------- 41.5/41.5 kB 2.0 MB/s eta 0:00:00
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence_transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: safetensors>=0.4.3 in c:\anaconda\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.8.0rc0)
Requirement already satisfied: anyio in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (4.2.0)
Requirement already satisfied: certifi in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (3.4)
Requirement already satisfied: h11>=0.16 in c:\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\anaconda\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: click>=8.2.1 in c:\anaconda\lib\site-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\anaconda\lib\site-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\anaconda\lib\site-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\anaconda\lib\site-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\anaconda\lib\site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\anaconda\lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\anaconda\lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (2.15.1)
Requirement already satisfied: sniffio>=1.1 in c:\anaconda\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in c:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (0.1.0)
Downloading sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
   ---------------------------------------- 0.0/596.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/596.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/596.4 kB ? eta -:--:--
    --------------------------------------- 10.2/596.4 kB ? eta -:--:--
   -- ------------------------------------ 41.0/596.4 kB 495.5 kB/s eta 0:00:02
   ------ -------------------------------- 92.2/596.4 kB 880.9 kB/s eta 0:00:01
   ------------- -------------------------- 204.8/596.4 kB 1.4 MB/s eta 0:00:01
   ------------------- -------------------- 286.7/596.4 kB 1.4 MB/s eta 0:00:01
   --------------------- ------------------ 317.4/596.4 kB 1.2 MB/s eta 0:00:01
   ------------------------ --------------- 368.6/596.4 kB 1.2 MB/s eta 0:00:01
   ---------------------------- ----------- 430.1/596.4 kB 1.2 MB/s eta 0:00:01
   ------------------------------ --------- 460.8/596.4 kB 1.2 MB/s eta 0:00:01
   ----------------------------------- ---- 532.5/596.4 kB 1.2 MB/s eta 0:00:01
   ------------------------------------ --- 542.7/596.4 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------  593.9/596.4 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 596.4/596.4 kB 1.0 MB/s eta 0:00:00
Downloading transformers-5.12.1-py3-none-any.whl (11.2 MB)
   ---------------------------------------- 0.0/11.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.2 MB 1.4 MB/s eta 0:00:09
   ---------------------------------------- 0.0/11.2 MB 667.8 kB/s eta 0:00:17
   ---------------------------------------- 0.0/11.2 MB 667.8 kB/s eta 0:00:17
   ---------------------------------------- 0.1/11.2 MB 658.7 kB/s eta 0:00:17
    --------------------------------------- 0.2/11.2 MB 700.2 kB/s eta 0:00:16
    --------------------------------------- 0.2/11.2 MB 765.3 kB/s eta 0:00:15
    --------------------------------------- 0.3/11.2 MB 811.7 kB/s eta 0:00:14
   - -------------------------------------- 0.3/11.2 MB 791.9 kB/s eta 0:00:14
   - -------------------------------------- 0.3/11.2 MB 819.2 kB/s eta 0:00:14
   - -------------------------------------- 0.3/11.2 MB 819.2 kB/s eta 0:00:14
   - -------------------------------------- 0.5/11.2 MB 954.4 kB/s eta 0:00:12
   - -------------------------------------- 0.6/11.2 MB 1.0 MB/s eta 0:00:11
   -- ------------------------------------- 0.6/11.2 MB 1.0 MB/s eta 0:00:11
   -- ------------------------------------- 0.6/11.2 MB 921.0 kB/s eta 0:00:12
   -- ------------------------------------- 0.7/11.2 MB 953.9 kB/s eta 0:00:11
   -- ------------------------------------- 0.7/11.2 MB 962.6 kB/s eta 0:00:11
   -- ------------------------------------- 0.8/11.2 MB 964.8 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/11.2 MB 996.1 kB/s eta 0:00:11
   --- ------------------------------------ 0.9/11.2 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.2 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.2 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.2 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.2 MB 973.9 kB/s eta 0:00:11
   --- ------------------------------------ 1.1/11.2 MB 960.3 kB/s eta 0:00:11
   ---- ----------------------------------- 1.1/11.2 MB 944.4 kB/s eta 0:00:11
   ---- ----------------------------------- 1.2/11.2 MB 966.2 kB/s eta 0:00:11
   ---- ----------------------------------- 1.2/11.2 MB 946.0 kB/s eta 0:00:11
   ---- ----------------------------------- 1.2/11.2 MB 932.3 kB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.2 MB 919.3 kB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.2 MB 920.9 kB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.2 MB 920.9 kB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.2 MB 902.1 kB/s eta 0:00:11
   ---- ----------------------------------- 1.4/11.2 MB 899.0 kB/s eta 0:00:11
   ----- ---------------------------------- 1.4/11.2 MB 891.6 kB/s eta 0:00:11
   ----- ---------------------------------- 1.4/11.2 MB 891.6 kB/s eta 0:00:11
   ----- ---------------------------------- 1.5/11.2 MB 864.1 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 858.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 854.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 830.7 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 830.7 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 805.9 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 805.9 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 805.9 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 805.9 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 805.9 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.2 MB 805.9 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.2 MB 721.9 kB/s eta 0:00:14
   ----- ---------------------------------- 1.6/11.2 MB 721.9 kB/s eta 0:00:14
   ----- ---------------------------------- 1.6/11.2 MB 700.9 kB/s eta 0:00:14
   ----- ---------------------------------- 1.6/11.2 MB 700.9 kB/s eta 0:00:14
   ----- ---------------------------------- 1.6/11.2 MB 677.4 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/11.2 MB 664.1 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/11.2 MB 655.6 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/11.2 MB 655.4 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/11.2 MB 655.4 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/11.2 MB 655.4 kB/s eta 0:00:15
   ------ --------------------------------- 1.7/11.2 MB 643.7 kB/s eta 0:00:15
   ------ --------------------------------- 1.7/11.2 MB 643.7 kB/s eta 0:00:15
   ------ --------------------------------- 1.8/11.2 MB 636.7 kB/s eta 0:00:15
   ------ --------------------------------- 1.8/11.2 MB 626.3 kB/s eta 0:00:15
   ------ --------------------------------- 1.8/11.2 MB 626.4 kB/s eta 0:00:15
   ------ --------------------------------- 1.8/11.2 MB 623.6 kB/s eta 0:00:15
   ------ --------------------------------- 1.8/11.2 MB 620.6 kB/s eta 0:00:16
   ------ --------------------------------- 1.9/11.2 MB 617.7 kB/s eta 0:00:16
   ------ --------------------------------- 1.9/11.2 MB 614.9 kB/s eta 0:00:16
   ------ --------------------------------- 1.9/11.2 MB 618.8 kB/s eta 0:00:15
   ------ --------------------------------- 1.9/11.2 MB 616.0 kB/s eta 0:00:15
   ------- -------------------------------- 2.0/11.2 MB 620.0 kB/s eta 0:00:15
   ------- -------------------------------- 2.0/11.2 MB 617.3 kB/s eta 0:00:15
   ------- -------------------------------- 2.0/11.2 MB 617.4 kB/s eta 0:00:15
   ------- -------------------------------- 2.1/11.2 MB 618.4 kB/s eta 0:00:15
   ------- -------------------------------- 2.1/11.2 MB 618.9 kB/s eta 0:00:15
   ------- -------------------------------- 2.1/11.2 MB 619.3 kB/s eta 0:00:15
   ------- -------------------------------- 2.1/11.2 MB 619.3 kB/s eta 0:00:15
   ------- -------------------------------- 2.2/11.2 MB 617.1 kB/s eta 0:00:15
   ------- -------------------------------- 2.2/11.2 MB 609.3 kB/s eta 0:00:15
   ------- -------------------------------- 2.2/11.2 MB 609.3 kB/s eta 0:00:15
   ------- -------------------------------- 2.2/11.2 MB 609.3 kB/s eta 0:00:15
   -------- ------------------------------- 2.2/11.2 MB 605.3 kB/s eta 0:00:15
   -------- ------------------------------- 2.3/11.2 MB 606.1 kB/s eta 0:00:15
   -------- ------------------------------- 2.3/11.2 MB 606.7 kB/s eta 0:00:15
   -------- ------------------------------- 2.3/11.2 MB 604.4 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.2 MB 607.7 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.2 MB 608.2 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.2 MB 606.0 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.2 MB 606.5 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.2 MB 604.6 kB/s eta 0:00:15
   -------- ------------------------------- 2.5/11.2 MB 600.6 kB/s eta 0:00:15
   --------- ------------------------------ 2.5/11.2 MB 603.7 kB/s eta 0:00:15
   --------- ------------------------------ 2.5/11.2 MB 599.3 kB/s eta 0:00:15
   --------- ------------------------------ 2.5/11.2 MB 599.3 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.2 MB 595.6 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.2 MB 598.6 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.2 MB 598.6 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.2 MB 590.3 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.2 MB 590.8 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.2 MB 582.9 kB/s eta 0:00:15
   --------- ------------------------------ 2.7/11.2 MB 579.3 kB/s eta 0:00:15
   --------- ------------------------------ 2.7/11.2 MB 579.9 kB/s eta 0:00:15
   --------- ------------------------------ 2.7/11.2 MB 576.2 kB/s eta 0:00:15
   --------- ------------------------------ 2.7/11.2 MB 576.8 kB/s eta 0:00:15
   --------- ------------------------------ 2.7/11.2 MB 576.8 kB/s eta 0:00:15
   ---------- ----------------------------- 2.8/11.2 MB 582.9 kB/s eta 0:00:15
   ---------- ----------------------------- 2.9/11.2 MB 587.8 kB/s eta 0:00:15
   ---------- ----------------------------- 2.9/11.2 MB 592.6 kB/s eta 0:00:14
   ---------- ----------------------------- 3.0/11.2 MB 597.5 kB/s eta 0:00:14
   ---------- ----------------------------- 3.0/11.2 MB 602.0 kB/s eta 0:00:14
   ---------- ----------------------------- 3.0/11.2 MB 602.5 kB/s eta 0:00:14
   ----------- ---------------------------- 3.1/11.2 MB 607.0 kB/s eta 0:00:14
   ----------- ---------------------------- 3.1/11.2 MB 607.4 kB/s eta 0:00:14
   ----------- ---------------------------- 3.2/11.2 MB 609.7 kB/s eta 0:00:14
   ----------- ---------------------------- 3.2/11.2 MB 610.1 kB/s eta 0:00:14
   ----------- ---------------------------- 3.2/11.2 MB 608.5 kB/s eta 0:00:14
   ----------- ---------------------------- 3.2/11.2 MB 608.5 kB/s eta 0:00:14
   ----------- ---------------------------- 3.2/11.2 MB 596.3 kB/s eta 0:00:14
   ----------- ---------------------------- 3.2/11.2 MB 598.6 kB/s eta 0:00:14
   ----------- ---------------------------- 3.3/11.2 MB 597.4 kB/s eta 0:00:14
   ----------- ---------------------------- 3.3/11.2 MB 601.4 kB/s eta 0:00:14
   ----------- ---------------------------- 3.3/11.2 MB 596.5 kB/s eta 0:00:14
   ------------ --------------------------- 3.3/11.2 MB 598.5 kB/s eta 0:00:14
   ------------ --------------------------- 3.4/11.2 MB 598.8 kB/s eta 0:00:13
   ------------ --------------------------- 3.4/11.2 MB 592.4 kB/s eta 0:00:14
   ------------ --------------------------- 3.4/11.2 MB 591.1 kB/s eta 0:00:14
   ------------ --------------------------- 3.4/11.2 MB 593.3 kB/s eta 0:00:14
   ------------ --------------------------- 3.5/11.2 MB 593.8 kB/s eta 0:00:13
   ------------ --------------------------- 3.5/11.2 MB 594.4 kB/s eta 0:00:13
   ------------ --------------------------- 3.5/11.2 MB 594.9 kB/s eta 0:00:13
   ------------ --------------------------- 3.5/11.2 MB 592.0 kB/s eta 0:00:13
   ------------ --------------------------- 3.6/11.2 MB 590.7 kB/s eta 0:00:13
   ------------ --------------------------- 3.6/11.2 MB 591.2 kB/s eta 0:00:13
   ------------ --------------------------- 3.6/11.2 MB 591.2 kB/s eta 0:00:13
   ------------ --------------------------- 3.6/11.2 MB 591.2 kB/s eta 0:00:13
   ------------ --------------------------- 3.6/11.2 MB 584.1 kB/s eta 0:00:13
   ------------- -------------------------- 3.6/11.2 MB 583.1 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.2 MB 580.6 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.2 MB 579.3 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.2 MB 579.7 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.2 MB 577.5 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.2 MB 576.4 kB/s eta 0:00:13
   ------------- -------------------------- 3.8/11.2 MB 576.6 kB/s eta 0:00:13
   ------------- -------------------------- 3.8/11.2 MB 576.6 kB/s eta 0:00:13
   ------------- -------------------------- 3.8/11.2 MB 573.4 kB/s eta 0:00:13
   ------------- -------------------------- 3.8/11.2 MB 573.4 kB/s eta 0:00:13
   ------------- -------------------------- 3.8/11.2 MB 571.4 kB/s eta 0:00:13
   ------------- -------------------------- 3.9/11.2 MB 571.8 kB/s eta 0:00:13
   ------------- -------------------------- 3.9/11.2 MB 569.3 kB/s eta 0:00:13
   ------------- -------------------------- 3.9/11.2 MB 567.1 kB/s eta 0:00:13
   -------------- ------------------------- 3.9/11.2 MB 566.2 kB/s eta 0:00:13
   -------------- ------------------------- 3.9/11.2 MB 563.9 kB/s eta 0:00:13
   -------------- ------------------------- 4.0/11.2 MB 564.5 kB/s eta 0:00:13
   -------------- ------------------------- 4.0/11.2 MB 563.6 kB/s eta 0:00:13
   -------------- ------------------------- 4.0/11.2 MB 561.6 kB/s eta 0:00:13
   -------------- ------------------------- 4.0/11.2 MB 563.0 kB/s eta 0:00:13
   -------------- ------------------------- 4.0/11.2 MB 560.9 kB/s eta 0:00:13
   -------------- ------------------------- 4.0/11.2 MB 560.9 kB/s eta 0:00:13
   -------------- ------------------------- 4.1/11.2 MB 559.6 kB/s eta 0:00:13
   -------------- ------------------------- 4.1/11.2 MB 559.6 kB/s eta 0:00:13
   -------------- ------------------------- 4.1/11.2 MB 559.0 kB/s eta 0:00:13

In [43]:
pip install --upgrade tqdm

Requirement already satisfied: tqdm in c:\anaconda\lib\site-packages (4.65.0)Note: you may need to restart the kernel to use updated packages.

Collecting tqdm
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.4 kB ? eta -:--:--
     ------- -------------------------------- 10.2/57.4 kB ? eta -:--:--
     ------------- ------------------------ 20.5/57.4 kB 108.9 kB/s eta 0:00:01
     -------------------- ----------------- 30.7/57.4 kB 145.2 kB/s eta 0:00:01
     --------------------------------- ---- 51.2/57.4 kB 200.8 kB/s eta 0:00:01
     -------------------------------------- 57.4/57.4 kB 188.5 kB/s eta 0:00:00
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from tqdm) (0.4.6)
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.3 kB ? eta -:--:--
   -------------------- ------------------- 41.0/78.3 kB 653.6 kB/s eta 0:00:01
   ---------------------------------------- 78.3/78.3 kB 862.0 kB/s eta 0:00:00
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
Successfully installed tqdm-4.68.3

## 1. Import

In [1]:
import pandas as pd
import numpy as np
import pickle

from sklearn.preprocessing import StandardScaler, OneHotEncoder, MultiLabelBinarizer
from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer

In [2]:
import warnings
from tqdm import TqdmWarning

warnings.filterwarnings("ignore", category=TqdmWarning)

## 1. Data loading

In [3]:
with open('hotels_preprocessed.pkl', 'rb') as file:
    hotels_preprocessed = pickle.load(file)

df_model = pd.DataFrame(hotels_preprocessed)

In [4]:
print(df_model.shape)
df_model.head()

(2470, 72)

,id,name,category_name,category_clean,hotel_stars,hotel_stars_for_model,pets_policy,has_pets_info,rooms_count_original,rooms_count,...,beach_services_count,beach_type,beach_type_has_info,beach_type_count,hotel_type,hotel_type_has_info,hotel_type_count,internet,internet_has_info,internet_count
0,23209,Gleam Collection,Special Category,special,NaN,unknown,unknown,0,60.0,60,...,0,[],0,0,[одно здание],1,1,[wi-fi в номере],1,1
1,23213,Eras Alanya,3*,star_hotel,3.0,3,unknown,0,0.0,120,...,0,[],0,0,[],0,0,[],0,0
2,23214,Club Dizalya,4*,star_hotel,4.0,4,unknown,0,331.0,331,...,1,"[галька, песок крупный]",1,2,[отельный комплекс/большая территория],1,1,"[wi-fi, wi-fi в номере]",1,2
3,23215,Hatipoglu Beach,3*,star_hotel,3.0,3,unknown,0,70.0,70,...,1,[песок жёлтый],1,1,[одно здание],1,1,[wi-fi],1,1
4,23216,Seven Seas Palmeras Bay,5*,star_hotel,5.0,5,unknown,0,324.0,324,...,1,[песок жёлтый],1,1,[отельный комплекс/большая территория],1,1,"[wi-fi, wi-fi в номере]",1,2

In [5]:
print('ID duplicates:', df_model['id'].duplicated().sum())
print('Missing IDs:', df_model['id'].isna().sum())
print('Missing names:', df_model['name'].isna().sum())

ID duplicates: 0
Missing IDs: 0
Missing names: 0

In [6]:
df_model[['id', 'name', 'canonical_text']].head()

,id,name,canonical_text
0,23209,Gleam Collection,hotel name: Gleam Collection. category: specia...
1,23213,Eras Alanya,hotel name: Eras Alanya. category: star_hotel....
2,23214,Club Dizalya,hotel name: Club Dizalya. category: star_hotel...
3,23215,Hatipoglu Beach,hotel name: Hatipoglu Beach. category: star_ho...
4,23216,Seven Seas Palmeras Bay,hotel name: Seven Seas Palmeras Bay. category:...

The data was successfully loaded from the pickle file. The pickle format is used to save processed Python objects without losing data types: in particular, service lists remain lists, not strings. This is important for further feature encoding and similarity calculation.

## 3. Feature-based representation

At this stage, a feature-based representation of hotels is constructed—a basic interpretable approach based on refined structured features.

The hotel vector includes:
- categorical features: category, star rating, pet policy, geographic cluster;
- numeric features: logarithmic number of rooms and flag indicating no information on the number of rooms;
- service lists encoded using MultiLabelBinarizer.

This approach is retained as a baseline because it reflects the original solution logic: comparing hotels based on explicitly defined characteristics. It will later be supplemented with an embedding-based approach based on canonical_text.

In [7]:
categorical_cols = [
    'category_clean',
    'hotel_stars_for_model',
    'pets_policy',
    'geo_cluster'
]

numeric_cols = [
    'rooms_count_log',
    'rooms_count_missing'
]

In [8]:
# List of columns with service groups
service_cols = [
    'common_services',
    'parking',
    'room_amenities',
    'special_rooms',
    'food_services',
    'transport',
    'laundry_services',
    'entertainment',
    'health_and_beauty',
    'pool',
    'beach_line',
    'sports',
    'business_services',
    'children_services',
    'beach_services',
    'beach_type',
    'hotel_type',
    'internet'
]

`service_info_share` and `service_info_count` are not included directly in the feature vector. These features do not reflect hotel characteristics, but rather the completeness of information about it. Therefore, they will be used later to assess the reliability of similarity, rather than as standard similarity features.

### 3.1 Transformation

#### 3.1.1 OneHotEncoder

In [9]:
cat_matrix = pd.get_dummies(
    df_model[categorical_cols],
    columns=categorical_cols,
    dummy_na=False
)

cat_matrix.shape

(2470, 33)

#### 3.1.2 StandardScaler

In [10]:
scaler = StandardScaler()

num_matrix = scaler.fit_transform(df_model[numeric_cols])

num_matrix.shape

(2470, 2)

#### 3.1.3 MultiLabelBinarizer

Each service block is encoded separately using the MultiLabelBinarizer. This allows information about which group a particular service belongs to to be preserved: for example, `pool__outdoor pool` and `food_services__restaurant` become separate attributes.

In [11]:
service_matrices = []
service_feature_names = []

mlb_dict = {}

for col in service_cols:
    mlb = MultiLabelBinarizer()
    
    col_matrix = mlb.fit_transform(df_model[col])
    
    service_matrices.append(col_matrix)
    
    col_feature_names = [col + '__' + item for item in mlb.classes_]
    service_feature_names.extend(col_feature_names)
    
    mlb_dict[col] = mlb

### 3.2 Final matrix

In [12]:
service_matrix = np.hstack(service_matrices)

service_matrix.shape

(2470, 178)

In [13]:
feature_matrix = np.hstack([
    cat_matrix.values,
    num_matrix,
    service_matrix
])

feature_matrix.shape

(2470, 213)

In [14]:
feature_names = (
    list(cat_matrix.columns) +
    numeric_cols +
    service_feature_names
)

print('Number of feature names:', len(feature_names))
print('Feature matrix columns:', feature_matrix.shape[1])
print('Check:', len(feature_names) == feature_matrix.shape[1])

Number of feature names: 213
Feature matrix columns: 213
Check: True

Feature names are stored separately to allow interpretation of the feature-based representation and, if necessary, analysis of which features influence the similarity of hotels.

### 3.3 Calculating similarity

In [15]:
feature_similarity_matrix = cosine_similarity(feature_matrix)

feature_similarity_matrix.shape

(2470, 2470)

Feature-based similarity is calculated using the cosine similarity between hotel feature vectors. The resulting matrix shows the degree of similarity between each hotel and all others based on structured features.

### 3.4 Saving artifacts

In [16]:
with open('feature_matrix.pkl', 'wb') as file:
    pickle.dump(feature_matrix, file)

with open('feature_similarity_matrix.pkl', 'wb') as file:
    pickle.dump(feature_similarity_matrix, file)

with open('feature_names.pkl', 'wb') as file:
    pickle.dump(feature_names, file)

with open('mlb_dict.pkl', 'wb') as file:
    pickle.dump(mlb_dict, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## 4. Embedding-based representation

At this stage, an embedding-based representation of the hotels is constructed. Unlike the feature-based approach, which compares hotels based on exact matches of encoded features, the embedding-based approach uses canonical_text—a unified textual description of each hotel.

The embedding model converts each text into a numeric vector. Hotels can then be compared based on the semantic similarity of their descriptions.

In [17]:
texts = df_model['canonical_text'].fillna('').tolist()

print('Number of texts:', len(texts))

Number of texts: 2470

In [18]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

### 4.1 Creating text embeddings

In this step, each canonical text is converted into an embedding—a numeric vector reflecting the semantic content of the hotel's text description. These vectors will later be used to calculate embedding-based similarity between hotels.

In [19]:
texts = df_model['canonical_text'].fillna('').tolist()

text_embeddings = model.encode(
    texts,
    batch_size=32,
    show_progress_bar=False,
    normalize_embeddings=True
)

text_embeddings.shape

(2470, 384)

### 4.2 Calculating similarity

After creating the embedding vectors, the similarity between all hotels can be calculated. This is done using cosine similarity. If two embedding vectors point close to each other, then the canonical text of these hotels is similar in meaning.

In [20]:
embedding_similarity_matrix = cosine_similarity(text_embeddings)

embedding_similarity_matrix.shape

(2470, 2470)

### 4.3 Saving

In [21]:
with open('text_embeddings.pkl', 'wb') as file:
    pickle.dump(text_embeddings, file)

with open('embedding_similarity_matrix.pkl', 'wb') as file:
    pickle.dump(embedding_similarity_matrix, file)

Embedding-based artifacts are preserved. `text_embeddings` contains the numeric representation of the canonical_text for each hotel, and `embedding_similarity_matrix` contains the pairwise similarity of all hotels based on their embedding vectors.

## 5. Combined similarity

This step combines two approaches to calculating hotel similarity:

1. `feature_similarity_matrix` — similarity by structured features: category, star rating, geography, number of rooms, and services.
2. `embedding_similarity_matrix` — similarity by semantic representation (canonical_text).

The feature-based approach preserves the interpretability of the original solution, while the embedding-based approach adds semantic comparison of the hotel text descriptions. Before combining, the ranges of values ​​in both matrices must be checked.

### 5.1 Preparing

In [22]:
print('Feature-based similarity:')
print('min:', feature_similarity_matrix.min())
print('max:', feature_similarity_matrix.max())
print('mean:', feature_similarity_matrix.mean())

print()

print('Embedding-based similarity:')
print('min:', embedding_similarity_matrix.min())
print('max:', embedding_similarity_matrix.max())
print('mean:', embedding_similarity_matrix.mean())

Feature-based similarity:
min: -0.14992183353451843
max: 1.0000000000000018
mean: 0.3924483949916099

Embedding-based similarity:
min: 0.33333272
max: 1.0000007
mean: 0.7877454

In [23]:
def min_max_normalize(matrix):
    matrix_min = matrix.min()
    matrix_max = matrix.max()
    
    normalized_matrix = (matrix - matrix_min) / (matrix_max - matrix_min)
    
    return normalized_matrix

In [24]:
feature_similarity_norm = min_max_normalize(feature_similarity_matrix)
embedding_similarity_norm = min_max_normalize(embedding_similarity_matrix)

In [25]:
print('Feature normalized:')
print('min:', feature_similarity_norm.min())
print('max:', feature_similarity_norm.max())

print()

print('Embedding normalized:')
print('min:', embedding_similarity_norm.min())
print('max:', embedding_similarity_norm.max())

Feature normalized:
min: 0.0
max: 1.0

Embedding normalized:
min: 0.0
max: 1.0

Both similarity matrices are scaled to a range between 0 and 1. This is necessary to ensure that when combining the feature-based and embedding-based approaches, neither receives artificially greater weight simply due to differences in the scale of the values.

### 5.2 Final similarity matrix

In [26]:
feature_weight = 0.3
embedding_weight = 0.7

In [27]:
final_similarity_matrix = (
    feature_weight * feature_similarity_norm +
    embedding_weight * embedding_similarity_norm
)

final_similarity_matrix.shape

(2470, 2470)

The final similarity matrix combines two sources of similarity: structural similarity based on purified features and semantic similarity based on canonical_text. The embedding-based approach carries a higher weight because it is the main refinement of the solution and reduces the dependence of recommendations on exact matches of sparse features.

## 6. Save modeling artifacts

In [28]:
with open('final_similarity_matrix.pkl', 'wb') as file:
    pickle.dump(final_similarity_matrix, file)

similarity_weights = {
    'feature_weight': feature_weight,
    'embedding_weight': embedding_weight
}

with open('similarity_weights.pkl', 'wb') as file:
    pickle.dump(similarity_weights, file)

In [29]:
with open('feature_similarity_norm.pkl', 'wb') as file:
    pickle.dump(feature_similarity_norm, file)

with open('embedding_similarity_norm.pkl', 'wb') as file:
    pickle.dump(embedding_similarity_norm, file)

During the modeling stage, two hotel representations were constructed: feature-based and embedding-based.

Feature-based similarity reflects similarity based on structured features: category, star rating, geography, number of rooms, and services. Embedding-based similarity reflects the semantic similarity of the canonical text generated during the preprocessing stage.

Both similarity matrices were normalized and combined into a final similarity matrix. This matrix will be used during the inference stage to generate recommendations.

Only the main artifacts were retained for further work: the final similarity matrix and the combined weights of the approaches.